
# Datasource
spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/wes

  username: postgres
  password:
  max-active: 10
  max-idle: 1
  min-idle: 1

spring:
  flyway:
    enabled: false